name: Auto Assignees and PR Reviewers

on:
  issues:
    types: [ opened ]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue assignees
        if: ${{ github.event_name == 'issues' }}
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
